const showsData = [
  {
    id: 1,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama7.jpg",
  },
  {
    id: 2,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 3,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 4,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 5,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 6,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 7,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 8,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 9,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 10,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 11,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 12,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 13,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 14,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 15,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 16,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 17,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 18,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 19,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 20,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 21,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 22,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 23,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 24,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 25,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 26,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 27,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 28,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 29,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 30,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 31,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 32,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
  {
    id: 33,
    title: "Sanda Eliya",
    date: "2025-06-20",
    time: "7:00 PM",
    city: "Kandy",
    location: "Royal Hall",
    image: "/images/drama2.jpg",
  },
  {
    id: 34,
    title: "Hiru Gala",
    date: "2025-06-21",
    time: "6:30 PM",
    city: "Colombo",
    location: "Nelum Pokuna",
    image: "/images/drama1.jpg",
  },
];

export default showsData;